name: Inference Pipeline

on:
  schedule:
    # Run daily at 6am UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      forecast_days:
        description: 'Number of days to forecast'
        required: true
        default: '7'
        type: choice
        options:
        - '1'
        - '3'
        - '7'
        - '14'
        - '30'

jobs:
  run_inference:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run inference
      env:
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        FORECAST_DAYS: ${{ github.event.inputs.forecast_days || '7' }}
      run: python run_inference.py --forecast-days $FORECAST_DAYS
      
    - name: Archive prediction results
      uses: actions/upload-artifact@v3
      with:
        name: predictions
        path: predictions/
        retention-days: 30
        
    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: inference-logs
        path: logs/
        retention-days: 7
